// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("BonusHistory")]
    [NUnit.Framework.CategoryAttribute("BonusHistory")]
    public partial class BonusHistoryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BonusHistory.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BonusHistory", null, ProgrammingLanguage.CSharp, new string[] {
                        "BonusHistory"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BonusHistory_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skybh1,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skybh2,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skybh3,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skybh4,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skybh5,a1234567", "\"\",All,01/03/2017,31/03/2017,50", "BonusHistoryFieldValidation", null, Category="source:Source\\BonusHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skybh6,a1234567", "Casino,All,01/03/2017,31/03/2017,50", "BonusHistoryTableResult", null, Category="source:Source\\BonusHistory.xlsx")]
        public virtual void BonusHistory_Scenario(string browser, string qAsites, string loginDetails, string details, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BonusHistory_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And("I click the my account link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I click bonus history link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("I provide the following {0}", details), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("I click the submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
