// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Casino")]
    [NUnit.Framework.CategoryAttribute("Casino")]
    public partial class CasinoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Casino.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Casino", null, ProgrammingLanguage.CSharp, new string[] {
                        "Casino"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Casino_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", null, Category="Source:Source\\Casino.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", null, Category="Source:Source\\Casino.xlsx")]
        public virtual void Casino_Scenario(string browser, string qAsites, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Casino_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.When("I click the casino link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.Then("I should see the casino page with game category listing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
