// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Deposit")]
    [NUnit.Framework.CategoryAttribute("Deposit")]
    public partial class DepositFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Deposit.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Deposit", null, ProgrammingLanguage.CSharp, new string[] {
                        "Deposit"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deposit_Scenario")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void Deposit_Scenario(string browser, string qAsites, string loginDetails, string details, string scenario, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ignore"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deposit_Scenario", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I click the deposit link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I click the neteller check box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I click the next button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And(string.Format("I provide the following {0}", details), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.When("I click the deposit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deposit_Neteller_Link")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skynl1,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skynl2,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skynl3,a1234567", null, Category="source:Source\\Deposit.xlsx")]
        public virtual void Deposit_Neteller_Link(string browser, string qAsites, string loginDetails, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deposit_Neteller_Link", exampleTags);
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("I click the deposit link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("I click the neteller check box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("I click the next button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.When("I click the click here hyperlink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.Then("I should see the neteller page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
