// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ForgotPassword")]
    [NUnit.Framework.CategoryAttribute("ForgotPassword")]
    public partial class ForgotPasswordFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ForgotPassword.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ForgotPassword", null, ProgrammingLanguage.CSharp, new string[] {
                        "ForgotPassword"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ForgotPassword_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "\"\",gerald.gono@test1.com", "ForgotUsernameIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skygg,\"\"", "ForgotEmailIsRequired", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "\"\",\"\"", "ForgotFieldValidation", null, Category="source:Source\\ForgotPassword.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skygg,gerald.gono@test1.com", "ForgotSuccess", null, Category="source:Source\\ForgotPassword.xlsx")]
        public virtual void ForgotPassword_Scenario(string browser, string qAsites, string details, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ForgotPassword_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.And("I click the forgot password link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And(string.Format("I provide the following {0}", details), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When("I click the send button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
