// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("GameHistory")]
    [NUnit.Framework.CategoryAttribute("GameHistory")]
    public partial class GameHistoryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GameHistory.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GameHistory", null, ProgrammingLanguage.CSharp, new string[] {
                        "GameHistory"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GameHistory_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skygh1,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skygh2,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skygh3,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skygh4,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skygh5,a1234567", "\"\",01/03/2017,31/03/2017,50", "GameHistoryFieldValidation", null, Category="source:Source\\GameHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skygh6,a1234567", "Quickfire,01/03/2017,31/03/2017,50", "GameHistoryTableResult", null, Category="source:Source\\GameHistory.xlsx")]
        public virtual void GameHistory_Scenario(string browser, string qAsites, string loginDetails, string details, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GameHistory_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And("I click the my account link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I click game history link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("I provide the following {0}", details), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("I click the submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
