// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("HeaderLinks")]
    [NUnit.Framework.CategoryAttribute("HeaderLinks")]
    public partial class HeaderLinksFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HeaderLinks.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HeaderLinks", null, ProgrammingLanguage.CSharp, new string[] {
                        "HeaderLinks"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("HeaderLinks_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "Deposit,bvs.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "MyAccount,bvs.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "Deposit,bvs.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "MyAccount,bvs.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "Deposit,bvs.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "MyAccount,bvs.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "Deposit,bte.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "MyAccount,bte.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "Deposit,bte.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "MyAccount,bte.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "Deposit,bte.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "MyAccount,bte.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "Deposit,stp.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "MyAccount,stp.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "Deposit,stp.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "MyAccount,stp.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "Deposit,stp.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "MyAccount,stp.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "Deposit,let.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "MyAccount,let.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "Deposit,let.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "MyAccount,let.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "Deposit,let.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "MyAccount,let.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "Deposit,ole.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "MyAccount,ole.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "Deposit,ole.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "MyAccount,ole.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "Deposit,ole.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "MyAccount,ole.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "Deposit,tbt.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "MyAccount,tbt.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "Deposit,tbt.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "MyAccount,tbt.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "Deposit,tbt.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "MyAccount,tbt.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "Deposit,fun.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "MyAccount,fun.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "Deposit,fun.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "MyAccount,fun.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "Deposit,fun.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "MyAccount,fun.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "Deposit,jen.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "MyAccount,jen.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "Deposit,jen.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "MyAccount,jen.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "Deposit,jen.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "MyAccount,jen.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "Deposit,set.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "MyAccount,set.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "Deposit,set.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "MyAccount,set.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "Deposit,set.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "MyAccount,set.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "Deposit,tlc.skyh1,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "MyAccount,tlc.skyh2,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "Deposit,tlc.skyh3,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "MyAccount,tlc.skyh4,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "SiteLogo", "HeaderLinkSiteLogo", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "ForgotPassword", "HeaderLinkForgot", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "Affiliates", "HeaderLinkAffiliates", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "Promotions", "HeaderLinkPromotions", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "Sportsbook", "HeaderLinkSportsbook", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "Casino", "HeaderLinkCasino", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "Deposit,tlc.skyh5,a1234567", "HeaderLinkDeposit", null, Category="source:Source\\HeaderLinks.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "MyAccount,tlc.skyh6,a1234567", "HeaderLinkMyAccount", null, Category="source:Source\\HeaderLinks.xlsx")]
        public virtual void HeaderLinks_Scenario(string browser, string qAsites, string details, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HeaderLinks_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.When(string.Format("I click this header link {0}", details), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
