// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Login")]
    [NUnit.Framework.CategoryAttribute("Login")]
    public partial class LoginFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Login.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Login", null, ProgrammingLanguage.CSharp, new string[] {
                        "Login"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Login_scenario")]
        [NUnit.Framework.TestCaseAttribute("bvs.skyl1", "a1234567", "LoginSuccess", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.skyl2", "a1234567", "LoginSuccess", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.skyl3", "a1234567", "LoginSuccess", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs", "a1234567", "LoginUserLessThan5", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs", "a1234567", "LoginUserLessThan5", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs", "a1234567", "LoginUserLessThan5", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky727sky727", "a1234567", "LoginUserGreaterThan12", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky727sky727", "a1234567", "LoginUserGreaterThan12", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky727sky727", "a1234567", "LoginUserGreaterThan12", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "", "LoginPassIsRequired", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "", "LoginPassIsRequired", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "", "LoginPassIsRequired", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "a123", "LoginPassLessThan6", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "a123", "LoginPassLessThan6", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "a123", "LoginPassLessThan6", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "a123456789", "LoginPassNotValid", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "a123456789", "LoginPassNotValid", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.leb2", "a123456789", "LoginPassNotValid", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky72727", "a1234567", "LoginUserNotValid", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky72727", "a1234567", "LoginUserNotValid", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky72727", "a1234567", "LoginUserNotValid", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky005", "a1234567", "LoginUnwanted", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky005", "a1234567", "LoginUnwanted", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky005", "a1234567", "LoginUnwanted", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky801", "a1234567", "LoginInactive", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky801", "a1234567", "LoginInactive", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky801", "a1234567", "LoginInactive", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky004", "a1234567", "LoginSuspended", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky004", "a1234567", "LoginSuspended", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky004", "a1234567", "LoginSuspended", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky001", "a1234567", "LoginSelfExcluded", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky001", "a1234567", "LoginSelfExcluded", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky001", "a1234567", "LoginSelfExcluded", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky455", "a1234567", "LoginTimeout", "chrome", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky455", "a1234567", "LoginTimeout", "firefox", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bvs.sky455", "a1234567", "LoginTimeout", "ie", "bvs", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.skyl1", "a1234567", "LoginSuccess", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.skyl2", "a1234567", "LoginSuccess", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.skyl3", "a1234567", "LoginSuccess", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte", "a1234567", "LoginUserLessThan5", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte", "a1234567", "LoginUserLessThan5", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte", "a1234567", "LoginUserLessThan5", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777sky777", "a1234567", "LoginUserGreaterThan12", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "", "LoginPassIsRequired", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "", "LoginPassIsRequired", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "", "LoginPassIsRequired", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "a123", "LoginPassLessThan6", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "a123", "LoginPassLessThan6", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "a123", "LoginPassLessThan6", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "a123456789", "LoginPassNotValid", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "a123456789", "LoginPassNotValid", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky777", "a123456789", "LoginPassNotValid", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky77727", "a1234567", "LoginUserNotValid", "chrome", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky77727", "a1234567", "LoginUserNotValid", "firefox", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("bte.sky77727", "a1234567", "LoginUserNotValid", "ie", "bte", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("stp.skyl1", "a1234567", "LoginSuccess", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("stp.skyl2", "a1234567", "LoginSuccess", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("stp.skyl3", "a1234567", "LoginSuccess", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp", "a1234567", "LoginUserLessThan5", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp", "a1234567", "LoginUserLessThan5", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp", "a1234567", "LoginUserLessThan5", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099sky777", "a1234567", "LoginUserGreaterThan12", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "", "LoginPassIsRequired", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "", "LoginPassIsRequired", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "", "LoginPassIsRequired", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "a123", "LoginPassLessThan6", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "a123", "LoginPassLessThan6", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "a123", "LoginPassLessThan6", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "a123456789", "LoginPassNotValid", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "a123456789", "LoginPassNotValid", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky099", "a123456789", "LoginPassNotValid", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky09927", "a1234567", "LoginUserNotValid", "chrome", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky09927", "a1234567", "LoginUserNotValid", "firefox", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sp.sky09927", "a1234567", "LoginUserNotValid", "ie", "stp", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.skyl1", "a1234567", "LoginSuccess", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.skyl2", "a1234567", "LoginSuccess", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.skyl3", "a1234567", "LoginSuccess", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let", "a1234567", "LoginUserLessThan5", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let", "a1234567", "LoginUserLessThan5", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let", "a1234567", "LoginUserLessThan5", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2sky777", "a1234567", "LoginUserGreaterThan12", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel!#(", "a1234567", "LoginSpecialCharacter", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel!#(", "a1234567", "LoginSpecialCharacter", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel!#(", "a1234567", "LoginSpecialCharacter", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "", "LoginPassIsRequired", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "", "LoginPassIsRequired", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "", "LoginPassIsRequired", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "a123", "LoginPassLessThan6", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "a123", "LoginPassLessThan6", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "a123", "LoginPassLessThan6", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "a123456789", "LoginPassNotValid", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "a123456789", "LoginPassNotValid", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel2", "a123456789", "LoginPassNotValid", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel227", "a1234567", "LoginUserNotValid", "chrome", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel227", "a1234567", "LoginUserNotValid", "firefox", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("let.bel227", "a1234567", "LoginUserNotValid", "ie", "let", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.skyl1", "a1234567", "LoginSuccess", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.skyl2", "a1234567", "LoginSuccess", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.skyl3", "a1234567", "LoginSuccess", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole", "a1234567", "LoginUserLessThan5", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole", "a1234567", "LoginUserLessThan5", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole", "a1234567", "LoginUserLessThan5", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005sky777", "a1234567", "LoginUserGreaterThan12", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "", "LoginPassIsRequired", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "", "LoginPassIsRequired", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "", "LoginPassIsRequired", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "a123", "LoginPassLessThan6", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "a123", "LoginPassLessThan6", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "a123", "LoginPassLessThan6", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "a123456789", "LoginPassNotValid", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "a123456789", "LoginPassNotValid", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky005", "a123456789", "LoginPassNotValid", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky00527", "a1234567", "LoginUserNotValid", "chrome", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky00527", "a1234567", "LoginUserNotValid", "firefox", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ole.sky00527", "a1234567", "LoginUserNotValid", "ie", "ole", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.skyl1", "a1234567", "LoginSuccess", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.skyl2", "a1234567", "LoginSuccess", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.skyl3", "a1234567", "LoginSuccess", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen", "a1234567", "LoginUserLessThan5", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen", "a1234567", "LoginUserLessThan5", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen", "a1234567", "LoginUserLessThan5", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748sky777", "a1234567", "LoginUserGreaterThan12", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "", "LoginPassIsRequired", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "", "LoginPassIsRequired", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "", "LoginPassIsRequired", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "a123", "LoginPassLessThan6", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "a123", "LoginPassLessThan6", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "a123", "LoginPassLessThan6", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "a123456789", "LoginPassNotValid", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "a123456789", "LoginPassNotValid", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky748", "a123456789", "LoginPassNotValid", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky74827", "a1234567", "LoginUserNotValid", "chrome", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky74827", "a1234567", "LoginUserNotValid", "firefox", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("jen.sky74827", "a1234567", "LoginUserNotValid", "ie", "jen", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.skyl1", "a1234567", "LoginSuccess", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.skyl2", "a1234567", "LoginSuccess", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.skyl3", "a1234567", "LoginSuccess", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set", "a1234567", "LoginUserLessThan5", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set", "a1234567", "LoginUserLessThan5", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set", "a1234567", "LoginUserLessThan5", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747sky777", "a1234567", "LoginUserGreaterThan12", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "", "LoginPassIsRequired", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "", "LoginPassIsRequired", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "", "LoginPassIsRequired", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "a123", "LoginPassLessThan6", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "a123", "LoginPassLessThan6", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "a123", "LoginPassLessThan6", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "a123456789", "LoginPassNotValid", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "a123456789", "LoginPassNotValid", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky747", "a123456789", "LoginPassNotValid", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky74727", "a1234567", "LoginUserNotValid", "chrome", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky74727", "a1234567", "LoginUserNotValid", "firefox", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("set.sky74727", "a1234567", "LoginUserNotValid", "ie", "set", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.skyl1", "a1234567", "LoginSuccess", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.skyl2", "a1234567", "LoginSuccess", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.skyl3", "a1234567", "LoginSuccess", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt", "a1234567", "LoginUserLessThan5", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt", "a1234567", "LoginUserLessThan5", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt", "a1234567", "LoginUserLessThan5", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747sky777", "a1234567", "LoginUserGreaterThan12", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "", "LoginPassIsRequired", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "", "LoginPassIsRequired", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "", "LoginPassIsRequired", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "a123", "LoginPassLessThan6", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "a123", "LoginPassLessThan6", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "a123", "LoginPassLessThan6", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "a123456789", "LoginPassNotValid", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "a123456789", "LoginPassNotValid", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "a123456789", "LoginPassNotValid", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky747", "a1234567", "LoginUserNotValid", "chrome", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky74727", "a1234567", "LoginUserNotValid", "firefox", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tbt.sky74727", "a1234567", "LoginUserNotValid", "ie", "tbt", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.skyl1", "a1234567", "LoginSuccess", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.skyl2", "a1234567", "LoginSuccess", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.skyl3", "a1234567", "LoginSuccess", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc", "a1234567", "LoginUserLessThan5", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc", "a1234567", "LoginUserLessThan5", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc", "a1234567", "LoginUserLessThan5", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747sky777", "a1234567", "LoginUserGreaterThan12", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "", "LoginPassIsRequired", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "", "LoginPassIsRequired", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "", "LoginPassIsRequired", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "a123", "LoginPassLessThan6", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "a123", "LoginPassLessThan6", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "a123", "LoginPassLessThan6", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "a123456789", "LoginPassNotValid", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "a123456789", "LoginPassNotValid", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky747", "a123456789", "LoginPassNotValid", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky74727", "a1234567", "LoginUserNotValid", "chrome", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky74727", "a1234567", "LoginUserNotValid", "firefox", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tlc.sky74727", "a1234567", "LoginUserNotValid", "ie", "tlc", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.skyl1", "a1234567", "LoginSuccess", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.skyl2", "a1234567", "LoginSuccess", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.skyl3", "a1234567", "LoginSuccess", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("", "a1234567", "LoginUserIsRequired", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun", "a1234567", "LoginUserLessThan5", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun", "a1234567", "LoginUserLessThan5", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun", "a1234567", "LoginUserLessThan5", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747sky777", "a1234567", "LoginUserGreaterThan12", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747sky777", "a1234567", "LoginUserGreaterThan12", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747sky777", "a1234567", "LoginUserGreaterThan12", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky!#(", "a1234567", "LoginSpecialCharacter", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky!#(", "a1234567", "LoginSpecialCharacter", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky!#(", "a1234567", "LoginSpecialCharacter", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "", "LoginPassIsRequired", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "", "LoginPassIsRequired", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "", "LoginPassIsRequired", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "a123", "LoginPassLessThan6", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "a123", "LoginPassLessThan6", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "a123", "LoginPassLessThan6", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "a123456789", "LoginPassNotValid", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "a123456789", "LoginPassNotValid", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky747", "a123456789", "LoginPassNotValid", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky74727", "a1234567", "LoginUserNotValid", "chrome", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky74727", "a1234567", "LoginUserNotValid", "firefox", "fun", null, Category="source:Source\\login.xlsx")]
        [NUnit.Framework.TestCaseAttribute("fun.sky74727", "a1234567", "LoginUserNotValid", "ie", "fun", null, Category="source:Source\\login.xlsx")]
        public virtual void Login_Scenario(string username, string password, string scenario, string browser, string qAsites, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login_scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.And(string.Format("I enter my Username using {0}", username), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And(string.Format("I enter my password using {0}", password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When("I click the login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
