// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("MyBonuses")]
    [NUnit.Framework.CategoryAttribute("MyBonuses")]
    public partial class MyBonusesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MyBonuses.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "MyBonuses", null, ProgrammingLanguage.CSharp, new string[] {
                        "MyBonuses"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MyBonuses_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skymb1,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skymb2,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skymb3,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skymb4,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skymb5,a1234567", "MyBonusesUrlVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skymb6,a1234567", "MyBonusesDetailsVerification", null, Category="source:Source\\MyBonuses.xlsx")]
        public virtual void MyBonuses_Scenario(string browser, string qAsites, string loginDetails, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MyBonuses_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And("I click the my account link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I click the my bonuses link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
