// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("MyDetails")]
    [NUnit.Framework.CategoryAttribute("MyDetails")]
    public partial class MyDetailsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MyDetails.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "MyDetails", null, ProgrammingLanguage.CSharp, new string[] {
                        "MyDetails"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MyDetails_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skymd1,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skymd2,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skymd3,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skymd4,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skymd5,a1234567", "MyDetailsUrlVerification", null, Category="source:Source\\MyDetails.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skymd6,a1234567", "MyDetailsDetailsVerification", null, Category="source:Source\\MyDetails.xlsx")]
        public virtual void MyDetails_Scenario(string browser, string qAsites, string loginDetails, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MyDetails_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And("I click the my account link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I click the my details link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
