// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Registration")]
    [NUnit.Framework.CategoryAttribute("Registration")]
    public partial class RegistrationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Registration.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Registration", null, ProgrammingLanguage.CSharp, new string[] {
                        "Registration"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registration_Url_Verification")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", null, Category="source:Source\\Registration.xlsx")]
        public virtual void Registration_Url_Verification(string browser, string qAsites, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registration_Url_Verification", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.When("I click the join now button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.Then("I should see the registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registration_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.test#", "RegistrationInvalidUsername(Format)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "a1234567,a123456", "RegistrationInvalidPassword(NotMatched)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "a123,a123", "RegistrationInvalidPassword(PasswordLength)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "test@test", "RegistrationInvalidEmail(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "9123456789a", "RegistrationInvalidMobileNumber(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "1234#", "RegistrationInvalidPostalCode(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "testingcity@", "RegistrationInvalidCity(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "Tester@", "RegistrationInvalidFirstName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "Test@", "RegistrationInvalidMiddleName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "Testing@", "RegistrationInvalidLastName(NotValid)", null, Category="source:Source\\Registration.xlsx")]
        public virtual void Registration_Scenario(string browser, string qAsites, string details, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registration_Scenario", exampleTags);
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
 testRunner.And("I click the join now button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And(string.Format("I provide the {0} depending on {1}", details, scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
