// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ResponsibleGaming")]
    [NUnit.Framework.CategoryAttribute("ResponsibleGaming")]
    public partial class ResponsibleGamingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ResponsibleGaming.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ResponsibleGaming", null, ProgrammingLanguage.CSharp, new string[] {
                        "ResponsibleGaming"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ResponsibleGaming_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skyrg18,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skyrg18,a1234567", "Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skyrg18,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skyrg18,a1234567", "Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skyrg18,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skyrg18,a1234567", "Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skyrg18,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skyrg18,a1234567", "Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skyrg18,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skyrg1,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skyrg3,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skyrg6,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skyrg7,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skyrg9,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skyrg12,a1234567", " Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skyrg13,a1234567", "1 hour", "RealityCheck", "RGChangeRealityCheck", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skyrg15,a1234567", "Limit by Month,\"\"", "DepositLimit", "RGDepositLimitFieldValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skyrg18,a1234567", "Yes", "TimeOut/SelfExclude", "RGTimeOutSelfExcludeValidation", null, Category="source:Source\\ResponsibleGaming.xlsx")]
        public virtual void ResponsibleGaming_Scenario(string browser, string qAsites, string loginDetails, string details, string category, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ResponsibleGaming_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And("I click the my account link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I click responsible gaming link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("I provide the {0} depending on {1}", details, scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When(string.Format("I click the {0} submit/save button", category), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
