// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TransactionHistory")]
    [NUnit.Framework.CategoryAttribute("TransactionHistory")]
    public partial class TransactionHistoryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TransactionHistory.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "TransactionHistory", null, ProgrammingLanguage.CSharp, new string[] {
                        "TransactionHistory"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TransactionHistory_Scenario")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skyth1,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skyth2,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skyth3,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skyth4,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skyth5,a1234567", "\"\",50,01/03/2017,31/03/2017", "TransactionHistoryFieldValidation", null, Category="source:Source\\TransactionHistory.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skyth6,a1234567", "Deposits and Withdrawal,50,01/03/2017,31/03/2017", "TransactionHistoryTableResult", null, Category="source:Source\\TransactionHistory.xlsx")]
        public virtual void TransactionHistory_Scenario(string browser, string qAsites, string loginDetails, string details, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TransactionHistory_Scenario", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And("I click the my account link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I click transaction history link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("I provide the following {0}", details), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("I click the submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
