// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AFT.Automation.UnitTest.Uk.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Withdraw")]
    [NUnit.Framework.CategoryAttribute("Withdraw")]
    public partial class WithdrawFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Withdraw.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Withdraw", null, ProgrammingLanguage.CSharp, new string[] {
                        "Withdraw"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Withdraw_Scenario")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void Withdraw_Scenario(string browser, string qAsites, string loginDetails, string amount, string details, string scenario, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ignore"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Withdraw_Scenario", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
    testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I click the my account link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I click the withdraw link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("I provide the withdraw amount {0}", amount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I click the withdraw next button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("I provide the following {0}", details), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.When("I click the withraw button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Withdraw_Validation")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bvs", "bvs.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bvs", "bvs.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bvs", "bvs.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "bte", "bte.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "bte", "bte.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "bte", "bte.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "stp", "stp.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "stp", "stp.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "stp", "stp.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "let", "let.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "let", "let.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "let", "let.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "ole", "ole.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "ole", "ole.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "ole", "ole.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "fun", "fun.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "fun", "fun.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "fun", "fun.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tbt", "tbt.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tbt", "tbt.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tbt", "tbt.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "jen", "jen.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "jen", "jen.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "jen", "jen.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "set", "set.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "set", "set.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "set", "set.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("chrome", "tlc", "tlc.skywv1,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("firefox", "tlc", "tlc.skywv2,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ie", "tlc", "tlc.skywv3,a1234567", "WithdrawValidation", null, Category="source:Source\\Withdraw.xlsx")]
        public virtual void Withdraw_Validation(string browser, string qAsites, string loginDetails, string scenario, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Withdraw_Validation", exampleTags);
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given(string.Format("I am on the home page of {0} and using {1}", qAsites, browser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
    testRunner.And(string.Format("I login using the following {0}", loginDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("I click the my account link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("I click the withdraw link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.Then(string.Format("I should see a message, redirect to another page, or see a details depending on {" +
                        "0}", scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
